version = 1

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "php"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "javascript"
